image:
  # -- image repository
  repository: ghcr.io/shizunge/endlessh-go
  # -- image tag
  tag: "2024.1106.0"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- See full list of command-line flags here: https://github.com/shizunge/endlessh-go/pkgs/container/endlessh-go#usage
# @default -- See values.yaml
args:
  - -enable_prometheus
  - -prometheus_port=2112
  - -port=2222
  - -logtostderr

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        enabled: true
        port: 2222
      http:
        enabled: true
        port: 2112
