env:
  PAPERLESS_REDIS: redis://redis-0.redis.databases.svc.cluster.local:6379
  PAPERLESS_DBHOST: postgres-0.postgres.databases.svc.cluster.local
  PAPERLESS_DBPORT: 5432
  PAPERLESS_DBNAME: app
  PAPERLESS_DBUSER: app
  PAPERLESS_DBPASS: apppassword

persistence:
  data:
    enabled: true
    type: emptyDir
  media:
    enabled: true
    type: emptyDir
  consume:
    enabled: true
    type: emptyDir
  export:
    enabled: true
    type: emptyDir
