image:
  # -- image repository
  repository: docuseal/docuseal
  # -- image tag
  tag: "2.3.3@sha256:b138638bd7324d2d5a50271dfd65e5519e6d088fd91822c1c9c2d06cb1d8328b"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [docuseal documentation](https://github.com/docusealco/docuseal).
# @default -- See below
env: {}
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
