{{ if not .Values.externalSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plausible-analytics.fullname" . }}
  labels:
    app: plausible
  {{- include "plausible-analytics.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (or .Values.postgresql.enabled .Values.postgresql.url) }}
  {{- if .Values.postgresql.url}}
  DATABASE_URL: {{ .Values.postgresql.url | toString | b64enc }}
  {{- else }}
  DATABASE_URL: {{ (printf "postgresql://%s:%s@%s-postgresql/%s" (.Values.postgresql.username | default "postgres") .Values.postgresql.auth.postgresPassword (include "plausible-analytics.fullname" .) (.Values.postgresql.auth.database | default "plausible")) | b64enc }}
  {{- end }}
  {{- end }}
  {{- if (or .Values.clickhouse.enabled .Values.clickhouse.url) }}
  {{- if .Values.clickhouse.url }}
  CLICKHOUSE_DATABASE_URL: {{ .Values.clickhouse.url | toString | b64enc }}
  {{- else }}
  CLICKHOUSE_DATABASE_URL: {{ (printf "http://%s-clickhouse:8123/plausible_events_db" (include "plausible-analytics.fullname" .)) | b64enc }}
  {{- end }}
  {{- end }}
  SECRET_KEY_BASE: {{ .Values.secretKey | default (randAlphaNum 90) | toString | b64enc }}
  TOTP_VAULT_KEY: {{ .Values.totpVaultKey | default (randAlphaNum 32) | trunc 32 | b64enc | b64enc}}
  {{- if .Values.smtp.enabled }}
  {{- if .Values.smtp.mailer.emailAddress }}
  MAILER_EMAIL: {{ .Values.smtp.mailer.emailAddress | toString | b64enc }}
  {{- end }}
  {{- if .Values.smtp.adapter }}
  MAILER_ADAPTER: {{ .Values.smtp.mailer.adapter | toString | b64enc }}
  {{- end }}
  {{- if .Values.smtp.host }}
  SMTP_HOST_ADDR: {{ .Values.smtp.host | toString | b64enc }}
  {{- end }}
  {{- if .Values.smtp.port }}
  SMTP_HOST_PORT: {{ .Values.smtp.port | toString | b64enc }}
  {{- end }}
  {{- if .Values.smtp.username }}
  SMTP_USER_NAME: {{ .Values.smtp.username | toString | b64enc }}
  {{- end }}
  {{- if .Values.smtp.password }}
  SMTP_USER_PWD: {{ .Values.smtp.password | toString | b64enc }}
  {{- end }}
  {{- if .Values.smtp.ssl.enabled }}
  SMTP_HOST_SSL_ENABLED: {{ .Values.smtp.ssl.enabled | toString | b64enc }}
  {{- end }}
  {{- if .Values.smtp.retries }}
  SMTP_RETRIES: {{ .Values.smtp.retries | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.google.clientID }}
  GOOGLE_CLIENT_ID: {{ .Values.google.clientID | toString | b64enc }}
  {{- end }}
  {{- if .Values.google.clientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.google.clientSecret | toString | b64enc }}
  {{- end }}
  {{- if .Values.twitter.consumer.key }}
  TWITTER_CONSUMER_KEY: {{ .Values.twitter.consumer.key | toString | b64enc }}
  {{- end }}
  {{- if .Values.twitter.consumer.secret }}
  TWITTER_CONSUMER_SECRET: {{ .Values.twitter.consumer.secret | toString | b64enc }}
  {{- end }}
  {{- if .Values.twitter.access.token }}
  TWITTER_ACCESS_TOKEN: {{ .Values.twitter.access.token | toString | b64enc }}
  {{- end }}
  {{- if .Values.twitter.access.secret }}
  TWITTER_ACCESS_TOKEN_SECRET: {{ .Values.twitter.access.secret | toString | b64enc }}
  {{- end }}
  {{- if .Values.postmark.apiKey }}
  POSTMARK_API_KEY: {{ .Values.postmark.apiKey | toString | b64enc }}
  {{- end }}
  {{- if .Values.geolocation.account_id }}
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.geolocation.account_id | toString | b64enc }}
  {{- end }}
  {{- if .Values.geolocation.license_key }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.geolocation.license_key | toString | b64enc }}
  {{- end }}
{{- end }}
