env:
  nocodb_REDIS: redis://redis:6379
  NC_DB: 'pg://postgresql:5432?u=app&p=apppassword&d=app'

persistence:
  data:
    enabled: true
    type: emptyDir
  media:
    enabled: true
    type: emptyDir
  consume:
    enabled: true
    type: emptyDir
  export:
    enabled: true
    type: emptyDir
